project:
  type: website

website:
  title: "Profit or Prestige EDA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda_0418.qmd
        text: Analysis

format:
  html:
    toc: true
    toc-depth: 4
    number-sections: true